In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv(r"B:\Datos\Estimulo\Dataset_Estimulo.csv")

display(data)
display()

,Timestamp,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.AF3.Gamma,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,...,POW.F8.Theta,POW.F8.Alpha,POW.F8.BetaL,POW.F8.BetaH,POW.F8.Gamma,POW.AF4.Theta,POW.AF4.Alpha,POW.AF4.BetaL,POW.AF4.BetaH,POW.AF4.Gamma
0,1.773267e+09,2.778698,2.005908,1.373546,0.494715,0.144563,2.703285,0.850476,1.250831,0.328245,...,1.911710,1.103620,0.814736,0.444735,0.171099,2.104374,1.564784,0.488283,0.265399,0.097376
1,1.773267e+09,3.290093,2.495170,1.745668,0.479406,0.146572,3.340949,1.173121,1.590586,0.323894,...,1.922565,1.273707,0.997767,0.432360,0.178313,2.100337,1.818033,0.568064,0.245971,0.098425
2,1.773267e+09,4.441703,2.811242,2.129460,0.469190,0.151403,4.421500,1.512068,1.907028,0.319837,...,1.883411,1.433821,1.138880,0.394725,0.186684,2.142040,1.998524,0.641751,0.220236,0.102870
3,1.773267e+09,6.076998,2.850644,2.431380,0.470695,0.156116,5.757320,1.777057,2.129900,0.321160,...,1.847964,1.533580,1.206429,0.335888,0.195280,2.261447,2.045461,0.703764,0.195703,0.112470
4,1.773267e+09,7.802941,2.591871,2.560771,0.482185,0.158811,7.004131,1.895283,2.213545,0.327183,...,1.863422,1.520124,1.185969,0.267166,0.203162,2.444337,1.922716,0.746196,0.177703,0.126983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11694,1.773844e+09,4.023157,1.348023,0.584214,0.098323,0.138287,6.277705,1.785643,0.920407,0.179653,...,2.128242,1.021597,0.312743,0.163708,0.205372,5.782043,3.409072,1.185879,0.271650,0.234204
11695,1.773844e+09,3.045411,1.090451,0.550299,0.090059,0.121030,5.090069,1.520687,0.886871,0.166535,...,1.574262,0.947028,0.263097,0.147508,0.202956,4.505837,3.078486,1.067027,0.265018,0.227981
11696,1.773844e+09,2.540573,1.027440,0.523045,0.086419,0.113549,4.311166,1.509581,0.835709,0.148711,...,1.225000,0.866662,0.231727,0.141189,0.208911,3.928746,2.853111,0.964458,0.263122,0.222197
11697,1.773844e+09,2.382291,1.110763,0.501670,0.087400,0.112526,3.906873,1.649366,0.783283,0.132607,...,1.069257,0.775275,0.220383,0.143776,0.219287,3.838524,2.636924,0.893453,0.263776,0.220523
11698,1.773844e+09,2.314561,1.253131,0.486554,0.092987,0.114143,3.628047,1.787762,0.736179,0.125917,...,1.017216,0.671338,0.221554,0.149615,0.228428,3.821916,2.348122,0.860124,0.261252,0.223370

In [ ]:
canales = ["AF3", "F7", "F3", "FC5", "FC6", "F4", "F8", "AF4", "P7", "O1", "O2", "P8"]
bandas  = ["Theta", "Alpha", "BetaL", "BetaH"]

columnas_filtradas = [f"POW.{canal}.{banda}" for canal in canales for banda in bandas]

dataf = data[columnas_filtradas]

display(dataf)

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
0,2.778698,2.005908,1.373546,0.494715,2.703285,0.850476,1.250831,0.328245,1.970482,2.372094,...,1.051430,0.499484,0.900508,1.575228,1.447638,0.611399,5.514122,2.059620,2.166949,0.748571
1,3.290093,2.495170,1.745668,0.479406,3.340949,1.173121,1.590586,0.323894,1.977424,2.642576,...,1.031023,0.432275,0.743763,1.383111,1.491731,0.608076,4.970300,1.956411,2.183315,0.815428
2,4.441703,2.811242,2.129460,0.469190,4.421500,1.512068,1.907028,0.319837,2.023658,2.779327,...,1.012733,0.353221,0.661332,1.269681,1.491125,0.575192,4.363361,1.940137,2.136524,0.859069
3,6.076998,2.850644,2.431380,0.470695,5.757320,1.777057,2.129900,0.321160,2.099698,2.696620,...,1.002651,0.281587,0.661121,1.194525,1.444105,0.525782,3.753525,1.993552,2.048418,0.878146
4,7.802941,2.591871,2.560771,0.482185,7.004131,1.895283,2.213545,0.327183,2.175836,2.380462,...,0.984906,0.229874,0.729829,1.097417,1.346478,0.478237,3.184816,2.030428,1.930055,0.868869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11694,4.023157,1.348023,0.584214,0.098323,6.277705,1.785643,0.920407,0.179653,1.594724,1.191007,...,0.600133,0.127343,3.458600,0.989282,0.684490,0.247966,2.332337,1.347254,0.720910,0.245381
11695,3.045411,1.090451,0.550299,0.090059,5.090069,1.520687,0.886871,0.166535,1.333209,1.154012,...,0.667258,0.132223,3.314622,0.988361,0.616705,0.195280,2.595242,1.439300,0.812962,0.244533
11696,2.540573,1.027440,0.523045,0.086419,4.311166,1.509581,0.835709,0.148711,1.238973,1.087492,...,0.811418,0.152308,3.095989,0.992629,0.603460,0.157268,2.952937,1.604022,1.014794,0.239964
11697,2.382291,1.110763,0.501670,0.087400,3.906873,1.649366,0.783283,0.132607,1.252975,1.007457,...,1.004675,0.189394,2.833671,1.024905,0.642605,0.140678,3.410474,1.820700,1.264901,0.229100
11698,2.314561,1.253131,0.486554,0.092987,3.628047,1.787762,0.736179,0.125917,1.291994,0.923708,...,1.180793,0.237072,2.596455,1.075006,0.708982,0.146147,3.894927,2.020141,1.474488,0.212775

In [8]:
dataf.info()

<class 'pandas.DataFrame'>
RangeIndex: 11699 entries, 0 to 11698
Data columns (total 48 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   POW.AF3.Theta  11699 non-null  float64
 1   POW.AF3.Alpha  11699 non-null  float64
 2   POW.AF3.BetaL  11699 non-null  float64
 3   POW.AF3.BetaH  11699 non-null  float64
 4   POW.F7.Theta   11699 non-null  float64
 5   POW.F7.Alpha   11699 non-null  float64
 6   POW.F7.BetaL   11699 non-null  float64
 7   POW.F7.BetaH   11699 non-null  float64
 8   POW.F3.Theta   11699 non-null  float64
 9   POW.F3.Alpha   11699 non-null  float64
 10  POW.F3.BetaL   11699 non-null  float64
 11  POW.F3.BetaH   11699 non-null  float64
 12  POW.FC5.Theta  11699 non-null  float64
 13  POW.FC5.Alpha  11699 non-null  float64
 14  POW.FC5.BetaL  11699 non-null  float64
 15  POW.FC5.BetaH  11699 non-null  float64
 16  POW.FC6.Theta  11699 non-null  float64
 17  POW.FC6.Alpha  11699 non-null  float64
 18  POW.FC6.BetaL  11699 non-null  float64
 19  POW.FC6.BetaH  11699 non-null  float64
 20  POW.F4.Theta   11699 non-null  float64
 21  POW.F4.Alpha   11699 non-null  float64
 22  POW.F4.BetaL   11699 non-null  float64
 23  POW.F4.BetaH   11699 non-null  float64
 24  POW.F8.Theta   11699 non-null  float64
 25  POW.F8.Alpha   11699 non-null  float64
 26  POW.F8.BetaL   11699 non-null  float64
 27  POW.F8.BetaH   11699 non-null  float64
 28  POW.AF4.Theta  11699 non-null  float64
 29  POW.AF4.Alpha  11699 non-null  float64
 30  POW.AF4.BetaL  11699 non-null  float64
 31  POW.AF4.BetaH  11699 non-null  float64
 32  POW.P7.Theta   11699 non-null  float64
 33  POW.P7.Alpha   11699 non-null  float64
 34  POW.P7.BetaL   11699 non-null  float64
 35  POW.P7.BetaH   11699 non-null  float64
 36  POW.O1.Theta   11699 non-null  float64
 37  POW.O1.Alpha   11699 non-null  float64
 38  POW.O1.BetaL   11699 non-null  float64
 39  POW.O1.BetaH   11699 non-null  float64
 40  POW.O2.Theta   11699 non-null  float64
 41  POW.O2.Alpha   11699 non-null  float64
 42  POW.O2.BetaL   11699 non-null  float64
 43  POW.O2.BetaH   11699 non-null  float64
 44  POW.P8.Theta   11699 non-null  float64
 45  POW.P8.Alpha   11699 non-null  float64
 46  POW.P8.BetaL   11699 non-null  float64
 47  POW.P8.BetaH   11699 non-null  float64
dtypes: float64(48)
memory usage: 4.3 MB

In [ ]:
Q1 = dataf.quantile(0.25)
Q3 = dataf.quantile(0.75)
IQR = Q3 - Q1

limite_inf = Q1 - 1.5 * IQR
limite_sup = Q3 + 1.5 * IQR

mask_outliers = (dataf < limite_inf) | (dataf > limite_sup)

filas_con_outliers = mask_outliers.any(axis=1)

print(f"Filas intervenidas: {filas_con_outliers.sum()}")

print("\n ANTES:")
display(dataf[filas_con_outliers])

df_limpio = dataf.copy()

for col in df_limpio.columns:
    mediana = df_limpio[col].median()
    df_limpio[col] = df_limpio[col].where(
        (df_limpio[col] >= limite_inf[col]) & (df_limpio[col] <= limite_sup[col]),
        other=mediana
    )

print("\n DESPUÉS:")
display(df_limpio[filas_con_outliers])

Filas intervenidas: 5936

 ANTES:

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
58,4.181222,0.882977,0.875799,0.304151,1.394062,1.149903,0.794337,0.261070,3.204310,0.550446,...,1.054402,0.332323,1.901993,1.695757,1.225492,0.439512,2.941842,1.523079,2.026515,0.541972
59,4.606531,0.786029,0.984412,0.343955,1.646304,1.097298,0.918405,0.275406,4.149312,0.585471,...,1.318351,0.410332,2.445057,2.091165,1.500541,0.568490,3.414916,1.769222,2.565928,0.682128
60,4.615892,0.712903,1.055906,0.389759,1.730084,0.979203,0.989282,0.285794,4.744234,0.605879,...,1.436415,0.460837,2.744668,2.302979,1.607671,0.655243,3.619053,1.952824,2.828067,0.795875
61,4.166427,0.670645,1.061352,0.426257,1.664760,0.823519,0.977091,0.287514,4.815858,0.597530,...,1.363525,0.470174,2.706107,2.242316,1.517145,0.674683,3.482044,1.958042,2.711763,0.858391
62,3.365517,0.659580,0.991575,0.444321,1.577759,0.686401,0.892797,0.279904,4.373734,0.573705,...,1.132348,0.436961,2.360234,1.924612,1.284037,0.625270,3.073861,1.752787,2.263255,0.856724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11684,6.992996,3.305342,1.389345,0.286202,9.043745,3.546728,1.670632,0.363281,9.166175,2.611378,...,1.247312,0.400526,2.380971,4.506586,2.918069,0.480317,10.065016,4.122150,1.100027,0.437601
11685,6.789275,3.916747,1.337799,0.269858,8.893222,3.829906,1.706575,0.344333,9.000801,3.077172,...,1.068864,0.328194,2.360088,3.954865,3.021053,0.442097,10.615720,3.852294,1.025955,0.399837
11686,6.694118,4.264959,1.178540,0.243219,8.626666,3.985060,1.543315,0.319894,8.186149,3.277468,...,0.865227,0.250214,2.244292,3.157899,2.886969,0.422741,10.302345,3.364843,1.003213,0.363186
11687,6.899415,4.322827,0.982699,0.211861,8.411566,4.041385,1.254851,0.287801,6.936421,3.133209,...,0.695571,0.182007,2.105489,2.310076,2.536821,0.416489,9.089507,2.756920,1.028568,0.335103
11688,7.411872,4.122470,0.817303,0.183423,8.423610,4.011833,0.957308,0.253658,5.588594,2.693891,...,0.595143,0.135447,2.102274,1.610846,2.070360,0.414464,7.257003,2.174314,1.067345,0.315438

 DESPUÉS:

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
58,4.181222,0.882977,0.875799,0.304151,1.394062,1.149903,0.794337,0.261070,3.204310,0.550446,...,1.054402,0.332323,1.901993,1.695757,1.225492,0.439512,2.941842,1.523079,2.026515,0.541972
59,4.606531,0.786029,0.984412,0.343955,1.646304,1.097298,0.918405,0.275406,4.149312,0.585471,...,1.318351,0.410332,2.445057,2.091165,1.500541,0.568490,3.414916,1.769222,2.565928,0.682128
60,4.615892,0.712903,1.055906,0.389759,1.730084,0.979203,0.989282,0.285794,4.744234,0.605879,...,1.436415,0.460837,2.744668,2.302979,1.607671,0.655243,3.619053,1.952824,2.828067,0.795875
61,4.166427,0.670645,1.061352,0.426257,1.664760,0.823519,0.977091,0.287514,4.815858,0.597530,...,1.363525,0.470174,2.706107,2.242316,1.517145,0.674683,3.482044,1.958042,2.711763,0.858391
62,3.365517,0.659580,0.991575,0.444321,1.577759,0.686401,0.892797,0.279904,4.373734,0.573705,...,1.132348,0.436961,2.360234,1.924612,1.284037,0.625270,3.073861,1.752787,2.263255,0.856724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11684,6.992996,3.305342,1.389345,0.286202,9.043745,3.546728,1.670632,0.363281,1.879576,2.611378,...,1.247312,0.400526,2.380971,1.124904,0.660584,0.480317,2.606238,4.122150,1.100027,0.437601
11685,6.789275,3.916747,1.337799,0.269858,8.893222,3.829906,1.706575,0.344333,1.879576,3.077172,...,1.068864,0.328194,2.360088,1.124904,0.660584,0.442097,2.606238,3.852294,1.025955,0.399837
11686,6.694118,4.264959,1.178540,0.243219,8.626666,3.985060,1.543315,0.319894,1.879576,3.277468,...,0.865227,0.250214,2.244292,3.157899,0.660584,0.422741,2.606238,3.364843,1.003213,0.363186
11687,6.899415,4.322827,0.982699,0.211861,8.411566,4.041385,1.254851,0.287801,6.936421,3.133209,...,0.695571,0.182007,2.105489,2.310076,0.660584,0.416489,2.606238,2.756920,1.028568,0.335103
11688,7.411872,4.122470,0.817303,0.183423,8.423610,4.011833,0.957308,0.253658,5.588594,2.693891,...,0.595143,0.135447,2.102274,1.610846,0.660584,0.414464,7.257003,2.174314,1.067345,0.315438

In [15]:
df_limpio.to_csv(r"B:\Datos\Estimulo\Dataset_Estimulo_filtrado.csv", index=False)
print("Guardado correctamente")

Guardado correctamente