In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv(r"B:\Datos\Basal\Dataset_Reposo.csv")

display(data)
display()

,Timestamp,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.AF3.Gamma,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,...,POW.F8.Theta,POW.F8.Alpha,POW.F8.BetaL,POW.F8.BetaH,POW.F8.Gamma,POW.AF4.Theta,POW.AF4.Alpha,POW.AF4.BetaL,POW.AF4.BetaH,POW.AF4.Gamma
0,1.773846e+09,1.704285,6.291201,0.290971,0.527793,0.296618,0.152611,0.035085,0.021609,0.062869,...,0.524482,3.879366,0.893351,0.516341,0.377801,2.006089,9.231936,0.659999,0.607215,0.376927
1,1.773846e+09,1.778737,6.058511,0.355458,0.577151,0.379075,0.138850,0.026901,0.022218,0.036955,...,0.638345,3.936423,1.089655,0.573651,0.443795,1.936150,9.297575,0.831810,0.681457,0.499639
2,1.773846e+09,1.940336,5.354917,0.428497,0.594831,0.504979,0.139482,0.028035,0.027090,0.023249,...,0.826247,3.814728,1.247117,0.617162,0.519409,1.975841,8.745917,0.997866,0.747042,0.665079
3,1.773846e+09,2.156696,4.383873,0.490324,0.575816,0.680622,0.152212,0.036432,0.036699,0.021016,...,1.058397,3.513108,1.294346,0.625999,0.612232,2.075784,7.729514,1.109622,0.782927,0.874717
4,1.773846e+09,2.379104,3.390968,0.552621,0.528882,0.896408,0.163523,0.049350,0.050305,0.026678,...,1.294064,3.060537,1.220509,0.592921,0.727026,2.202016,6.474143,1.181123,0.778028,1.116037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11971,1.773798e+09,0.892137,0.830987,1.261028,0.243904,0.090725,1.684692,2.062524,1.432431,0.279873,...,0.852760,0.836866,1.705447,0.488688,0.129800,3.745452,2.332908,2.237530,0.557249,0.134639
11972,1.773798e+09,0.748158,0.795567,1.103629,0.224715,0.089029,2.073607,1.860494,1.450195,0.269128,...,0.718118,0.690103,1.515336,0.451403,0.128622,3.479942,2.545044,1.966321,0.517066,0.143862
11973,1.773798e+09,0.695550,0.828653,0.870368,0.202555,0.086600,2.504179,1.645963,1.361823,0.255152,...,0.694797,0.573794,1.232020,0.378856,0.125245,3.132490,2.602589,1.581466,0.449552,0.144582
11974,1.773798e+09,0.688795,0.884959,0.646364,0.182586,0.084087,2.806744,1.427622,1.214542,0.238937,...,0.728112,0.505776,0.966543,0.293947,0.121793,2.703813,2.483286,1.195697,0.371593,0.136926
11975,1.773798e+09,0.690444,0.914407,0.506555,0.165608,0.081828,2.856508,1.204903,1.068317,0.221156,...,0.788126,0.491616,0.815890,0.217162,0.120045,2.246815,2.217728,0.908833,0.296943,0.123533

In [ ]:
canales = ["AF3", "F7", "F3", "FC5", "FC6", "F4", "F8", "AF4", "P7", "O1", "O2", "P8"]
bandas  = ["Theta", "Alpha", "BetaL", "BetaH"]

columnas_filtradas = [f"POW.{canal}.{banda}" for canal in canales for banda in bandas]

dataf = data[columnas_filtradas]

display(dataf)

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
0,1.704285,6.291201,0.290971,0.527793,0.152611,0.035085,0.021609,0.062869,0.827835,3.961967,...,0.309069,0.333286,0.641913,0.622759,0.427321,0.307243,0.870422,1.766997,0.846709,0.442609
1,1.778737,6.058511,0.355458,0.577151,0.138850,0.026901,0.022218,0.036955,0.809170,3.926246,...,0.287866,0.361555,0.759894,0.591080,0.500060,0.313986,0.948491,1.769151,0.937139,0.448701
2,1.940336,5.354917,0.428497,0.594831,0.139482,0.028035,0.027090,0.023249,0.913623,3.669479,...,0.317602,0.402541,0.868874,0.622299,0.573160,0.341553,1.038144,1.624048,1.045465,0.466263
3,2.156696,4.383873,0.490324,0.575816,0.152212,0.036432,0.036699,0.021016,1.122923,3.291819,...,0.373228,0.454742,0.927536,0.679926,0.609082,0.389715,1.101560,1.348876,1.130117,0.474722
4,2.379104,3.390968,0.552621,0.528882,0.163523,0.049350,0.050305,0.026678,1.353487,2.885693,...,0.441208,0.512714,0.914080,0.720717,0.586645,0.450114,1.116623,1.013788,1.155486,0.460151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11971,0.892137,0.830987,1.261028,0.243904,1.684692,2.062524,1.432431,0.279873,0.422484,0.256337,...,0.134153,0.082341,0.665549,0.414124,0.198305,0.065162,3.202798,1.149326,0.919884,0.304235
11972,0.748158,0.795567,1.103629,0.224715,2.073607,1.860494,1.450195,0.269128,0.551987,0.301904,...,0.102482,0.091195,0.770540,0.430714,0.176216,0.069404,3.004525,1.171197,0.792671,0.281056
11973,0.695550,0.828653,0.870368,0.202555,2.504179,1.645963,1.361823,0.255152,0.653829,0.327546,...,0.083836,0.096977,0.836118,0.416191,0.144503,0.071357,2.764429,1.119260,0.618034,0.242282
11974,0.688795,0.884959,0.646364,0.182586,2.806744,1.427622,1.214542,0.238937,0.697668,0.324966,...,0.084190,0.097982,0.844821,0.367308,0.114113,0.070560,2.551381,0.991968,0.475962,0.200283
11975,0.690444,0.914407,0.506555,0.165608,2.856508,1.204903,1.068317,0.221156,0.677884,0.300935,...,0.103827,0.094003,0.793202,0.292029,0.094752,0.067766,2.396372,0.809587,0.427408,0.165933

In [4]:
dataf.info()

<class 'pandas.DataFrame'>
RangeIndex: 11976 entries, 0 to 11975
Data columns (total 48 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   POW.AF3.Theta  11976 non-null  float64
 1   POW.AF3.Alpha  11976 non-null  float64
 2   POW.AF3.BetaL  11976 non-null  float64
 3   POW.AF3.BetaH  11976 non-null  float64
 4   POW.F7.Theta   11976 non-null  float64
 5   POW.F7.Alpha   11976 non-null  float64
 6   POW.F7.BetaL   11976 non-null  float64
 7   POW.F7.BetaH   11976 non-null  float64
 8   POW.F3.Theta   11976 non-null  float64
 9   POW.F3.Alpha   11976 non-null  float64
 10  POW.F3.BetaL   11976 non-null  float64
 11  POW.F3.BetaH   11976 non-null  float64
 12  POW.FC5.Theta  11976 non-null  float64
 13  POW.FC5.Alpha  11976 non-null  float64
 14  POW.FC5.BetaL  11976 non-null  float64
 15  POW.FC5.BetaH  11976 non-null  float64
 16  POW.FC6.Theta  11976 non-null  float64
 17  POW.FC6.Alpha  11976 non-null  float64
 18  POW.FC6.BetaL  11976 non-null  float64
 19  POW.FC6.BetaH  11976 non-null  float64
 20  POW.F4.Theta   11976 non-null  float64
 21  POW.F4.Alpha   11976 non-null  float64
 22  POW.F4.BetaL   11976 non-null  float64
 23  POW.F4.BetaH   11976 non-null  float64
 24  POW.F8.Theta   11976 non-null  float64
 25  POW.F8.Alpha   11976 non-null  float64
 26  POW.F8.BetaL   11976 non-null  float64
 27  POW.F8.BetaH   11976 non-null  float64
 28  POW.AF4.Theta  11976 non-null  float64
 29  POW.AF4.Alpha  11976 non-null  float64
 30  POW.AF4.BetaL  11976 non-null  float64
 31  POW.AF4.BetaH  11976 non-null  float64
 32  POW.P7.Theta   11976 non-null  float64
 33  POW.P7.Alpha   11976 non-null  float64
 34  POW.P7.BetaL   11976 non-null  float64
 35  POW.P7.BetaH   11976 non-null  float64
 36  POW.O1.Theta   11976 non-null  float64
 37  POW.O1.Alpha   11976 non-null  float64
 38  POW.O1.BetaL   11976 non-null  float64
 39  POW.O1.BetaH   11976 non-null  float64
 40  POW.O2.Theta   11976 non-null  float64
 41  POW.O2.Alpha   11976 non-null  float64
 42  POW.O2.BetaL   11976 non-null  float64
 43  POW.O2.BetaH   11976 non-null  float64
 44  POW.P8.Theta   11976 non-null  float64
 45  POW.P8.Alpha   11976 non-null  float64
 46  POW.P8.BetaL   11976 non-null  float64
 47  POW.P8.BetaH   11976 non-null  float64
dtypes: float64(48)
memory usage: 4.4 MB

In [ ]:
Q1 = dataf.quantile(0.25)
Q3 = dataf.quantile(0.75)
IQR = Q3 - Q1

limite_inf = Q1 - 1.5 * IQR
limite_sup = Q3 + 1.5 * IQR

mask_outliers = (dataf < limite_inf) | (dataf > limite_sup)

filas_con_outliers = mask_outliers.any(axis=1)

print(f"Filas intervenidas: {filas_con_outliers.sum()}")

print("\n ANTES:")
display(dataf[filas_con_outliers])

df_limpio = dataf.copy()

for col in df_limpio.columns:
    mediana = df_limpio[col].median()
    df_limpio[col] = df_limpio[col].where(
        (df_limpio[col] >= limite_inf[col]) & (df_limpio[col] <= limite_sup[col]),
        other=mediana
    )

print("\n DESPUÉS:")
display(df_limpio[filas_con_outliers])

Filas intervenidas: 6811

 ANTES:

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
0,1.704285,6.291201,0.290971,0.527793,0.152611,0.035085,0.021609,0.062869,0.827835,3.961967,...,0.309069,0.333286,0.641913,0.622759,0.427321,0.307243,0.870422,1.766997,0.846709,0.442609
1,1.778737,6.058511,0.355458,0.577151,0.138850,0.026901,0.022218,0.036955,0.809170,3.926246,...,0.287866,0.361555,0.759894,0.591080,0.500060,0.313986,0.948491,1.769151,0.937139,0.448701
2,1.940336,5.354917,0.428497,0.594831,0.139482,0.028035,0.027090,0.023249,0.913623,3.669479,...,0.317602,0.402541,0.868874,0.622299,0.573160,0.341553,1.038144,1.624048,1.045465,0.466263
3,2.156696,4.383873,0.490324,0.575816,0.152212,0.036432,0.036699,0.021016,1.122923,3.291819,...,0.373228,0.454742,0.927536,0.679926,0.609082,0.389715,1.101560,1.348876,1.130117,0.474722
4,2.379104,3.390968,0.552621,0.528882,0.163523,0.049350,0.050305,0.026678,1.353487,2.885693,...,0.441208,0.512714,0.914080,0.720717,0.586645,0.450114,1.116623,1.013788,1.155486,0.460151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11970,1.140349,0.953128,1.293983,0.253974,1.456270,2.219244,1.303691,0.285644,0.306828,0.207350,...,0.170421,0.072755,0.547715,0.376587,0.203384,0.059620,3.296734,1.068197,0.942066,0.302662
11971,0.892137,0.830987,1.261028,0.243904,1.684692,2.062524,1.432431,0.279873,0.422484,0.256337,...,0.134153,0.082341,0.665549,0.414124,0.198305,0.065162,3.202798,1.149326,0.919884,0.304235
11972,0.748158,0.795567,1.103629,0.224715,2.073607,1.860494,1.450195,0.269128,0.551987,0.301904,...,0.102482,0.091195,0.770540,0.430714,0.176216,0.069404,3.004525,1.171197,0.792671,0.281056
11973,0.695550,0.828653,0.870368,0.202555,2.504179,1.645963,1.361823,0.255152,0.653829,0.327546,...,0.083836,0.096977,0.836118,0.416191,0.144503,0.071357,2.764429,1.119260,0.618034,0.242282
11974,0.688795,0.884959,0.646364,0.182586,2.806744,1.427622,1.214542,0.238937,0.697668,0.324966,...,0.084190,0.097982,0.844821,0.367308,0.114113,0.070560,2.551381,0.991968,0.475962,0.200283

 DESPUÉS:

,POW.AF3.Theta,POW.AF3.Alpha,POW.AF3.BetaL,POW.AF3.BetaH,POW.F7.Theta,POW.F7.Alpha,POW.F7.BetaL,POW.F7.BetaH,POW.F3.Theta,POW.F3.Alpha,...,POW.O1.BetaL,POW.O1.BetaH,POW.O2.Theta,POW.O2.Alpha,POW.O2.BetaL,POW.O2.BetaH,POW.P8.Theta,POW.P8.Alpha,POW.P8.BetaL,POW.P8.BetaH
0,1.704285,6.291201,0.290971,0.527793,0.152611,0.035085,0.021609,0.062869,0.827835,0.899903,...,0.309069,0.333286,0.641913,0.622759,0.427321,0.307243,0.870422,1.766997,0.846709,0.442609
1,1.778737,6.058511,0.355458,0.577151,0.138850,0.026901,0.022218,0.036955,0.809170,0.899903,...,0.287866,0.361555,0.759894,0.591080,0.500060,0.313986,0.948491,1.769151,0.937139,0.448701
2,1.940336,5.354917,0.428497,0.594831,0.139482,0.028035,0.027090,0.023249,0.913623,0.899903,...,0.317602,0.402541,0.868874,0.622299,0.573160,0.341553,1.038144,1.624048,1.045465,0.466263
3,2.156696,4.383873,0.490324,0.575816,0.152212,0.036432,0.036699,0.021016,1.122923,0.899903,...,0.373228,0.454742,0.927536,0.679926,0.609082,0.389715,1.101560,1.348876,1.130117,0.474722
4,2.379104,3.390968,0.552621,0.528882,0.163523,0.049350,0.050305,0.026678,1.353487,2.885693,...,0.441208,0.512714,0.914080,0.720717,0.586645,0.450114,1.116623,1.013788,1.155486,0.460151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11970,1.140349,0.953128,1.293983,0.253974,1.456270,2.219244,1.303691,0.285644,0.306828,0.207350,...,0.170421,0.072755,0.547715,0.376587,0.203384,0.059620,3.296734,1.068197,0.942066,0.302662
11971,0.892137,0.830987,1.261028,0.243904,1.684692,2.062524,0.480455,0.279873,0.422484,0.256337,...,0.134153,0.082341,0.665549,0.414124,0.198305,0.065162,3.202798,1.149326,0.919884,0.304235
11972,0.748158,0.795567,1.103629,0.224715,2.073607,1.860494,0.480455,0.269128,0.551987,0.301904,...,0.102482,0.091195,0.770540,0.430714,0.176216,0.069404,3.004525,1.171197,0.792671,0.281056
11973,0.695550,0.828653,0.870368,0.202555,2.504179,1.645963,1.361823,0.255152,0.653829,0.327546,...,0.083836,0.096977,0.836118,0.416191,0.144503,0.071357,2.764429,1.119260,0.618034,0.242282
11974,0.688795,0.884959,0.646364,0.182586,2.806744,1.427622,1.214542,0.238937,0.697668,0.324966,...,0.084190,0.097982,0.844821,0.367308,0.114113,0.070560,2.551381,0.991968,0.475962,0.200283

In [8]:
df_limpio.to_csv(r"B:\Datos\Basal\Dataset_Reposo_filtrado.csv", index=False)
print("Guardado correctamente")

Guardado correctamente